services:
    app:
      build:
        context: .
      volumes:
        - ./backend:/app
      env_file:
        - .env
      ports:
        - "8888:8000"
      restart: on-failure
      command: >
          sh -c "python manage.py db_waiter && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  

    db:
      image: mysql:8
      env_file:
        - .env
      ports:
        - "3307:3306"
      volumes:
        - ./mysql:/var/lib/mysql
      restart: on-failure

    redis:
      image: redis:alpine

    celery:
      build:
        context: .
      volumes:
        - ./backend:/app
      env_file:
        - .env
      restart: on-failure
      command: >
        sh -c "export DJANGO_SETTINGS_MODULE=configs.settings && celery -A configs worker -l info"
      
