services:
  db:
    image: mysql:8
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

  redis:
    image: redis:alpine

  celery:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "celery -A configs worker -l info -B"
