# Generated by Django 5.1.5 on 2025-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
