# Generated by Django 5.1.4 on 2025-01-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_rename_seze_pizzamodel_size_pizzamodel_created_at_and_more'),
        ('pizza_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='pizza_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.pizzashopmodel'),
            preserve_default=False,
        ),
    ]
