# Generated by Django 5.1.4 on 2025-01-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_pizzamodel_day_alter_pizzamodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='photos',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
