# Generated by Django 5.1.5 on 2025-02-03 13:31

import core.services.file_service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizzamodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzamodel',
            name='photos',
        ),
        migrations.AddField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_pizza_photo),
        ),
    ]
