# Generated by Django 5.1.4 on 2024-12-31 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzamodel',
            old_name='seze',
            new_name='size',
        ),
        migrations.AddField(
            model_name='pizzamodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzamodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='pizzamodel',
            table='pizzas',
        ),
    ]
