# Generated by Django 5.1.4 on 2025-01-04 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_pizzamodel_pizza_shop'),
        ('pizza_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{1,19}$', 'Only alpha characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='pizza_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizza_shop.pizzashopmodel'),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
